displayName: Cloudflare DDNS Plugin
type: middleware

import: github.com/xdsorite/ddns-traefik-plugin

summary: Automatically sync DNS records with Cloudflare

testData:
  enabled: true
  zone: example.com
  apiToken: CHANGE_ME
  syncIntervalSeconds: 300
  requestTimeoutSeconds: 10
  autoDiscoverHost: true
  routerRule: Host(`app.example.com`)
  domains:
    - api.example.com
  domainsCsv: app2.example.com,app3.example.com
  defaultProxied: false
  ipSources:
    - https://api.ipify.org
